# Generated by Django 5.2 on 2025-05-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('GBP', 'GBP')], default='USD', max_length=3),
        ),
    ]
