# Generated by Django 5.2 on 2025-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_items_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
