# Generated by Django 5.2 on 2025-05-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_user_alter_teammember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
    ]
