# Generated by Django 5.2 on 2025-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_teammember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
