# Generated by Django 5.2 on 2025-05-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammember_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
