# Generated by Django 5.2 on 2025-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('GBP', 'GBP')], default='USD', max_length=3),
        ),
    ]
