# Generated by Django 5.2 on 2025-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticketcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(choices=[('technical_support', 'Technical Support'), ('billing_issue', 'Billing Issue'), ('account_management', 'Account Management'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('general_inquiry', 'General Inquiry')], max_length=100),
        ),
    ]
